### ISSUE TITLE
Unique key is being expected for credit type abbreviation on v4.0.0

### ISSUE THREAD

**Issue by kaustubhkapatral** [regen-network/regen-ledger#1187]
## Summary of Bug

While creating a new credit class on a devnet with mainnet export, the tx fails with the following error 

```
raw_log: 'failed to execute message; message index: 0: unique key violation'
timestamp: "2022-06-15T09:59:44Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount:
      - amount: "20"
        denom: uregen
      gas_limit: "200000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: AvnM2dfST0M94PSkoNo2NaI9Jx0CIu4VYIcYd+nTqW83
      sequence: "65"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /regen.ecocredit.v1.MsgCreateClass
      admin: regen1qwa9xy0997j5mrc4dxn7jrcvvkpm3uwuldkrmg
      credit_type_abbrev: C
      fee:
        amount: "20000000"
        denom: uregen
      issuers:
      - regen1j0wl83ulvwancndjg5jp3r5l2m8jq0fap88ew0
      - regen108fuazrugwhvf9sxknn2r5nyv24vaetaensyhc
      - regen132hlyt0uwnl6sy9esrerdf0gtmhex6ephc2mwq
      - regen1qwa9xy0997j5mrc4dxn7jrcvvkpm3uwuldkrmg
      metadata: cmVnZW4K
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
```
The tx which was submitted to create a new class was this:
```
regen tx ecocredit create-class regen1j0wl83ulvwancndjg5jp3r5l2m8jq0fap88ew0,regen108fuazrugwhvf9sxknn2r5nyv24vaetaensyhc,regen132hlyt0uwnl6sy9esrerdf0gtmhex6ephc2mwq,regen1qwa9xy0997j5mrc4dxn7jrcvvkpm3uwuldkrmg C cmVnZW4K 20000000uregen --from val-1 --fees 20uregen --chain-id 4.0-test -y
```

The tx can be queried here :
 http://194.37.81.19:1317/txs/D6F53A62FCF403ACCE31BBA1A5ABD1E97198BD3C6F0CA7029E607A1952E7AF20

## Version
`v4.0.0`

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
