### ISSUE TITLE
Sell order with `nil` expiration returns invalid expiration date

### ISSUE THREAD

**Issue by aleem1314** [regen-network/regen-ledger#1272]
## Summary of Bug

Querying sell order with `nil` expiration is returning invalid expiration date.

```
sell_order:
  ask_amount: "1"
  ask_denom: uregen
  batch_denom: C06-001-20221206-20231212-001
  disable_auto_retire: false
  expiration: "1970-01-01T00:00:00Z"
  id: "5"
  quantity: "2"
  seller: regen156d26rl52y3wl865pr5x9q2vqetuw9kf0642sa
```

## Version

v4.0.0-rc1

## Steps to Reproduce

1. Create a `sell` order with `nil` expiration.
2. Query `sell-order` by order-id.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
