### ISSUE TITLE
Basket curator incorrect address after redwood state migration

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1280]
## Summary

Basket curator addresses following migration on redwood are not valid addresses:

```
baskets_info:
- basket_denom: eco.uC.rNCT
  curator: regen1wfjkwetwx9jxvd3hx4erjanwvcmhqer9v3hrgumxxgm8xanywdjk6vm4vashvemcd4ungdsa96fkg
- basket_denom: eco.uC.NCT
  curator: regen1wfjkwetwx9jxvd3hx4erjanwvcmhqer9v3hrgumxxgm8xanywdjk6vm4vashvemcd4ungdsa96fkg
- basket_denom: eco.uC.TYLER
  curator: regen1wfjkwetwx9uhzu3swpnrxwrk894rwctgxuuhwmttv93kzaf4d4j8xurnvvmkcvrndfjhvcgw7f86e
```

The addresses should be:

```
baskets_info:
- basket_denom: eco.uC.rNCT
  curator: regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46
- basket_denom: eco.uC.NCT
  curator: regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46
- basket_denom: eco.uC.TYLER
  curator: regen1yqr0pf38v9j7ah79wmkacau5mdspsc7l0sjeva
```

## Version

`v4.0.0-rc1`

## Steps to Reproduce

https://hackmd.io/WauavR3jR0uzj8gfxoIP6Q
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
