### ISSUE TITLE
After upgrading from "v1.0.0" to "v2.0.0-rc3", credit class fee expects a fee in "stake" denom

### ISSUE THREAD

**Issue by kaustubhkapatral** [regen-network/regen-ledger#590]
## Summary of Bug

After upgrading the network from `v1.0.0` to `v2.0.0-rc3`, default ecocredit params expects the fee to be in `stake` denom instead of `uregen`.

```
regen query ecocredit params
params:
  allowed_class_creators: []
  allowlist_enabled: false
  credit_class_fee:
  - amount: "20000000"
    denom: stake
  credit_types:
  - abbreviation: C
    name: carbon
    precision: 6
    unit: metric ton CO2 equivalent

```

## Version

`v2.0.0-rc3`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
